// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn6fdLwHICPQAnvxlnjo7MRh2ErTfoUvk',
    appId: '1:1069483869025:web:fb16c88c1d3bc868843b20',
    messagingSenderId: '1069483869025',
    projectId: 'marketplace-app-v2-c03a2',
    authDomain: 'marketplace-app-v2-c03a2.firebaseapp.com',
    storageBucket: 'marketplace-app-v2-c03a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBzMEjyXZUIFGac_1-mA0nbCVB6nJXtZ0',
    appId: '1:1069483869025:android:2e4027867a13db1a843b20',
    messagingSenderId: '1069483869025',
    projectId: 'marketplace-app-v2-c03a2',
    storageBucket: 'marketplace-app-v2-c03a2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrwpHpbnazTyZV0cpwSsWA77CfD5677rA',
    appId: '1:1069483869025:ios:3fafed13816a9707843b20',
    messagingSenderId: '1069483869025',
    projectId: 'marketplace-app-v2-c03a2',
    storageBucket: 'marketplace-app-v2-c03a2.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrwpHpbnazTyZV0cpwSsWA77CfD5677rA',
    appId: '1:1069483869025:ios:3fafed13816a9707843b20',
    messagingSenderId: '1069483869025',
    projectId: 'marketplace-app-v2-c03a2',
    storageBucket: 'marketplace-app-v2-c03a2.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn6fdLwHICPQAnvxlnjo7MRh2ErTfoUvk',
    appId: '1:1069483869025:web:44858091d4210390843b20',
    messagingSenderId: '1069483869025',
    projectId: 'marketplace-app-v2-c03a2',
    authDomain: 'marketplace-app-v2-c03a2.firebaseapp.com',
    storageBucket: 'marketplace-app-v2-c03a2.firebasestorage.app',
  );
}
