// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP2011V17abq1aQ3ORzg3RhIEVEOJVbYE',
    appId: '1:2037911947:web:954cbb8026cb2cf6b2df8e',
    messagingSenderId: '2037911947',
    projectId: 'marketplace-app-a9156',
    authDomain: 'marketplace-app-a9156.firebaseapp.com',
    storageBucket: 'marketplace-app-a9156.firebasestorage.app',
    measurementId: 'G-BKEQN9G6G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZWesXAiuRV07H3OtVoTuU27SGXt4IqHQ',
    appId: '1:2037911947:android:e2526df318094f0bb2df8e',
    messagingSenderId: '2037911947',
    projectId: 'marketplace-app-a9156',
    storageBucket: 'marketplace-app-a9156.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbNsIkodQuk4txIkUk1-gl0opm2x1rDHA',
    appId: '1:2037911947:ios:14c3056b5976d0e3b2df8e',
    messagingSenderId: '2037911947',
    projectId: 'marketplace-app-a9156',
    storageBucket: 'marketplace-app-a9156.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbNsIkodQuk4txIkUk1-gl0opm2x1rDHA',
    appId: '1:2037911947:ios:14c3056b5976d0e3b2df8e',
    messagingSenderId: '2037911947',
    projectId: 'marketplace-app-a9156',
    storageBucket: 'marketplace-app-a9156.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP2011V17abq1aQ3ORzg3RhIEVEOJVbYE',
    appId: '1:2037911947:web:4d8fc319e50c8c40b2df8e',
    messagingSenderId: '2037911947',
    projectId: 'marketplace-app-a9156',
    authDomain: 'marketplace-app-a9156.firebaseapp.com',
    storageBucket: 'marketplace-app-a9156.firebasestorage.app',
    measurementId: 'G-64S1MHXGCF',
  );
}
